#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PORT=42420

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT}" \
        s6-setuidgid abc /server/VintagestoryServer --dataPath /config
